//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corrupto.SvcDataProvider.DonsPartiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/corrupto", ConfigurationName="DonsPartiServiceReference.corruptoSoap")]
    public interface corruptoSoap {
        
        // CODEGEN: Generating message contract since element name strCommand from namespace http://tempuri.org/corrupto is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/corrupto/InterrogerCorrupto", ReplyAction="*")]
        Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse InterrogerCorrupto(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/corrupto/InterrogerCorrupto", ReplyAction="*")]
        System.Threading.Tasks.Task<Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse> InterrogerCorruptoAsync(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InterrogerCorruptoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InterrogerCorrupto", Namespace="http://tempuri.org/corrupto", Order=0)]
        public Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequestBody Body;
        
        public InterrogerCorruptoRequest() {
        }
        
        public InterrogerCorruptoRequest(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/corrupto")]
    public partial class InterrogerCorruptoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCommand;
        
        public InterrogerCorruptoRequestBody() {
        }
        
        public InterrogerCorruptoRequestBody(string strCommand) {
            this.strCommand = strCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InterrogerCorruptoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InterrogerCorruptoResponse", Namespace="http://tempuri.org/corrupto", Order=0)]
        public Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponseBody Body;
        
        public InterrogerCorruptoResponse() {
        }
        
        public InterrogerCorruptoResponse(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/corrupto")]
    public partial class InterrogerCorruptoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InterrogerCorruptoResult;
        
        public InterrogerCorruptoResponseBody() {
        }
        
        public InterrogerCorruptoResponseBody(string InterrogerCorruptoResult) {
            this.InterrogerCorruptoResult = InterrogerCorruptoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface corruptoSoapChannel : Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class corruptoSoapClient : System.ServiceModel.ClientBase<Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap>, Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap {
        
        public corruptoSoapClient() {
        }
        
        public corruptoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public corruptoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public corruptoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public corruptoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap.InterrogerCorrupto(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest request) {
            return base.Channel.InterrogerCorrupto(request);
        }
        
        public string InterrogerCorrupto(string strCommand) {
            Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest inValue = new Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest();
            inValue.Body = new Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequestBody();
            inValue.Body.strCommand = strCommand;
            Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse retVal = ((Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap)(this)).InterrogerCorrupto(inValue);
            return retVal.Body.InterrogerCorruptoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse> Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap.InterrogerCorruptoAsync(Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest request) {
            return base.Channel.InterrogerCorruptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoResponse> InterrogerCorruptoAsync(string strCommand) {
            Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest inValue = new Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequest();
            inValue.Body = new Corrupto.SvcDataProvider.DonsPartiServiceReference.InterrogerCorruptoRequestBody();
            inValue.Body.strCommand = strCommand;
            return ((Corrupto.SvcDataProvider.DonsPartiServiceReference.corruptoSoap)(this)).InterrogerCorruptoAsync(inValue);
        }
    }
}
